# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0002_auto_20170811_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssection',
            name='SLogo',
            field=models.CharField(default='logo.png', max_length=50),
        ),
    ]
