# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0003_newssection_slogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='lastlogin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
