# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-21 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0006_auto_20170822_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isadmin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
