# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWS', '0007_auto_20170822_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='eventdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
